# Generated by Django 5.1.1 on 2024-09-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encryption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('encrypted_content', models.TextField(blank=True)),
                ('decrypted_content', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('uk', 'Ukrainian'), ('en', 'English')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
