# Generated by Django 5.1.1 on 2024-09-14 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0002_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryption',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_app.file'),
        ),
    ]
