# Generated by Django 5.1.1 on 2024-09-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0003_alter_encryption_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryption',
            name='key',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
