# Generated by Django 5.1.1 on 2024-09-14 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0004_encryption_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
    ]
