# Generated by Django 5.1.1 on 2024-09-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0005_remove_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryption',
            name='key',
            field=models.TextField(),
        ),
    ]
